name: blobgram
description: A product demo of client side routing, made with blobs.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  faker: ^2.0.0
  auto_route: ^3.2.4
  build_runner: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  
flutter:
  uses-material-design: true